#ifndef VERSION_UTILS_H_IN
#define VERSION_UTILS_H_IN

#define EYS3D_DEPTH_VERSION_MAJOR 1
#define EYS3D_DEPTH_VERSION_MINOR 0
#define EYS3D_DEPTH_VERSION_PATCH 0
#define EYS3D_DEPTH_VERSION_TWEAK 1

#define WRAPPER_VERSION "1.0.0.1"
#define GIT_BRANCH "diff_sz_point_cloud"
#define GIT_HASH "2fe628e"
#define BUILD_TIMESTAMP "2021-08-23 11:26:59"

#endif // VERSION_UTILS_H_IN
