SET VENDOR_SDK_ROOT=..\..\..
echo %VENDOR_SDK_ROOT%

SET EYS3D_PYTHON_LIB=%VENDOR_SDK_ROOT%\libeYs3D\wrapper\python
echo %EYS3D_PYTHON_LIB%

SET PYTHONPATH=%VENDOR_SDK_ROOT%\libeYs3D\out;%EYS3D_PYTHON_LIB%
echo %PYTHONPATH%

SET EYS3D_SDK_HOME=%VENDOR_SDK_ROOT%\libeYs3D\out\eYs3D\
echo %EYS3D_SDK_HOME%

SET EYS3D_HOME=%VENDOR_SDK_ROOT%\libeYs3D\out\eYs3D\
echo %EYS3D_HOME%

python sample_code\demo.py -m %1 -i %2 --depth-bit %3

SET PYTHONPATH=""
SET EYS3D_PYTHON_LIB=""
SET VENDOR_SDK_ROOT=""
SET EYS3D_SDK_HOME=""
SET EYS3D_HOME=""